"""pump det updated2

Revision ID: 053f818d176c
Revises: f3e1bc61a0fa
Create Date: 2025-03-24 11:32:58.838417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053f818d176c'
down_revision = 'f3e1bc61a0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.String(length=255), nullable=False))
        batch_op.alter_column('lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)
        batch_op.alter_column('long',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)

    with op.batch_alter_table('savedlocs', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)
        batch_op.alter_column('long',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('home_lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('home_long',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('work_lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('work_long',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('work_long',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('work_lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('home_long',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('home_lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('savedlocs', schema=None) as batch_op:
        batch_op.alter_column('long',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.alter_column('long',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###
