"""clipbord

Revision ID: 251faca4ba9a
Revises: 25d798a897f4
Create Date: 2025-03-18 08:56:04.464489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251faca4ba9a'
down_revision = '25d798a897f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('home_lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('home_long',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('work_lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('work_long',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('work_long',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('work_lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('home_long',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('home_lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.drop_table('clipboards')
    # ### end Alembic commands ###
