"""pump det updated

Revision ID: f3e1bc61a0fa
Revises: e013ff86ce77
Create Date: 2025-03-24 11:27:14.771268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e1bc61a0fa'
down_revision = 'e013ff86ce77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pumps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(precision=6), nullable=False),
    sa.Column('long', sa.Float(precision=6), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savedlocs', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)
        batch_op.alter_column('long',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('home_lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('home_long',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('work_lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
        batch_op.alter_column('work_long',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('work_long',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('work_lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('home_long',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('home_lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('savedlocs', schema=None) as batch_op:
        batch_op.alter_column('long',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('pumps')
    # ### end Alembic commands ###
